// GENERATED CODE - DO NOT MODIFY BY HAND
import 'package:flutter/widgets.dart';

const iconDefinitions = {
  "_R_light": Icon(IconData(0xE001, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_R": Icon(IconData(0xE001, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_argdown_light": Icon(
      IconData(0xE003, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_argdown": Icon(IconData(0xE003, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_asm_light": Icon(IconData(0xE004, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_asm": Icon(IconData(0xE004, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_audio_light": Icon(
      IconData(0xE005, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_audio": Icon(IconData(0xE005, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_babel_light": Icon(
      IconData(0xE006, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_babel": Icon(IconData(0xE006, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_bower_light": Icon(
      IconData(0xE007, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_bower": Icon(IconData(0xE007, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_bsl_light": Icon(IconData(0xE008, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_bsl": Icon(IconData(0xE008, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_c_light": Icon(IconData(0xE00A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_c": Icon(IconData(0xE00A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_c-sharp_light": Icon(
      IconData(0xE009, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_c-sharp": Icon(IconData(0xE009, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_c_1_light": Icon(IconData(0xE00A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_c_1": Icon(IconData(0xE00A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_c_2_light": Icon(IconData(0xE00A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_c_2": Icon(IconData(0xE00A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_cake_light": Icon(IconData(0xE00B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_cake": Icon(IconData(0xE00B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_cake_php_light": Icon(
      IconData(0xE00C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_cake_php": Icon(IconData(0xE00C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_clock_light": Icon(
      IconData(0xE010, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_clock": Icon(IconData(0xE010, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_clock_1_light": Icon(
      IconData(0xE010, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff627379)),
  "_clock_1": Icon(IconData(0xE010, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff6d8086)),
  "_clojure_light": Icon(
      IconData(0xE011, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_clojure": Icon(IconData(0xE011, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_clojure_1_light": Icon(
      IconData(0xE011, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_clojure_1": Icon(IconData(0xE011, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_code-climate_light": Icon(
      IconData(0xE012, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_code-climate": Icon(
      IconData(0xE012, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_coffee_light": Icon(
      IconData(0xE013, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_coffee": Icon(IconData(0xE013, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_coldfusion_light": Icon(
      IconData(0xE015, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_coldfusion": Icon(IconData(0xE015, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_config_light": Icon(
      IconData(0xE016, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff627379)),
  "_config": Icon(IconData(0xE016, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff6d8086)),
  "_cpp_light": Icon(IconData(0xE017, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_cpp": Icon(IconData(0xE017, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_cpp_1_light": Icon(
      IconData(0xE017, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_cpp_1": Icon(IconData(0xE017, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_cpp_2_light": Icon(
      IconData(0xE017, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_cpp_2": Icon(IconData(0xE017, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_crystal_light": Icon(
      IconData(0xE018, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffbfc2c1)),
  "_crystal": Icon(IconData(0xE018, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffd4d7d6)),
  "_crystal_embedded_light": Icon(
      IconData(0xE019, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffbfc2c1)),
  "_crystal_embedded": Icon(
      IconData(0xE019, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffd4d7d6)),
  "_css_light": Icon(IconData(0xE01A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_css": Icon(IconData(0xE01A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_csv_light": Icon(IconData(0xE01B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_csv": Icon(IconData(0xE01B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_d_light": Icon(IconData(0xE01C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_d": Icon(IconData(0xE01C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_dart_light": Icon(IconData(0xE01D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_dart": Icon(IconData(0xE01D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_db_light": Icon(IconData(0xE01E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffdd4b78)),
  "_db": Icon(IconData(0xE01E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xfff55385)),
  "_default_light": Icon(
      IconData(0xE01F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffbfc2c1)),
  "_default": Icon(IconData(0xE01F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffd4d7d6)),
  "_docker_light": Icon(
      IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_docker": Icon(IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_docker_1_light": Icon(
      IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff455155)),
  "_docker_1": Icon(IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff4d5a5e)),
  "_docker_2_light": Icon(
      IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_docker_2": Icon(IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_docker_3_light": Icon(
      IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffdd4b78)),
  "_docker_3": Icon(IconData(0xE021, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xfff55385)),
  "_ejs_light": Icon(IconData(0xE023, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_ejs": Icon(IconData(0xE023, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_elixir_light": Icon(
      IconData(0xE024, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_elixir": Icon(IconData(0xE024, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_elixir_script_light": Icon(
      IconData(0xE025, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_elixir_script": Icon(
      IconData(0xE025, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_elm_light": Icon(IconData(0xE026, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_elm": Icon(IconData(0xE026, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_eslint_light": Icon(
      IconData(0xE028, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_eslint": Icon(IconData(0xE028, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_eslint_1_light": Icon(
      IconData(0xE028, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff455155)),
  "_eslint_1": Icon(IconData(0xE028, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff4d5a5e)),
  "_ethereum_light": Icon(
      IconData(0xE029, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_ethereum": Icon(IconData(0xE029, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_f-sharp_light": Icon(
      IconData(0xE02A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_f-sharp": Icon(IconData(0xE02A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_favicon_light": Icon(
      IconData(0xE02B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_favicon": Icon(IconData(0xE02B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_firebase_light": Icon(
      IconData(0xE02C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_firebase": Icon(IconData(0xE02C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_firefox_light": Icon(
      IconData(0xE02D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_firefox": Icon(IconData(0xE02D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_font_light": Icon(IconData(0xE02F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_font": Icon(IconData(0xE02F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_git_light": Icon(IconData(0xE030, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff3b4b52)),
  "_git": Icon(IconData(0xE030, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff41535b)),
  "_go_light": Icon(IconData(0xE034, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_go": Icon(IconData(0xE034, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_go2_light": Icon(IconData(0xE035, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_go2": Icon(IconData(0xE035, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_gradle_light": Icon(
      IconData(0xE036, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_gradle": Icon(IconData(0xE036, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_grails_light": Icon(
      IconData(0xE037, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_grails": Icon(IconData(0xE037, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_graphql_light": Icon(
      IconData(0xE038, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffdd4b78)),
  "_graphql": Icon(IconData(0xE038, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xfff55385)),
  "_grunt_light": Icon(
      IconData(0xE039, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_grunt": Icon(IconData(0xE039, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_gulp_light": Icon(IconData(0xE03A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_gulp": Icon(IconData(0xE03A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_haml_light": Icon(IconData(0xE03C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_haml": Icon(IconData(0xE03C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_happenings_light": Icon(
      IconData(0xE03D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_happenings": Icon(IconData(0xE03D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_haskell_light": Icon(
      IconData(0xE03E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_haskell": Icon(IconData(0xE03E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_haxe_light": Icon(IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_haxe": Icon(IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_haxe_1_light": Icon(
      IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_haxe_1": Icon(IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_haxe_2_light": Icon(
      IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_haxe_2": Icon(IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_haxe_3_light": Icon(
      IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_haxe_3": Icon(IconData(0xE03F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_heroku_light": Icon(
      IconData(0xE040, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_heroku": Icon(IconData(0xE040, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_hex_light": Icon(IconData(0xE041, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_hex": Icon(IconData(0xE041, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_html_light": Icon(IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_html": Icon(IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_html_1_light": Icon(
      IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_html_1": Icon(IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_html_2_light": Icon(
      IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_html_2": Icon(IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_html_3_light": Icon(
      IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_html_3": Icon(IconData(0xE042, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_html_erb_light": Icon(
      IconData(0xE043, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_html_erb": Icon(IconData(0xE043, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_ignored_light": Icon(
      IconData(0xE044, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff3b4b52)),
  "_ignored": Icon(IconData(0xE044, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff41535b)),
  "_illustrator_light": Icon(
      IconData(0xE045, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_illustrator": Icon(
      IconData(0xE045, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_image_light": Icon(
      IconData(0xE046, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_image": Icon(IconData(0xE046, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_info_light": Icon(IconData(0xE047, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_info": Icon(IconData(0xE047, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_ionic_light": Icon(
      IconData(0xE048, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_ionic": Icon(IconData(0xE048, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_jade_light": Icon(IconData(0xE049, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_jade": Icon(IconData(0xE049, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_java_light": Icon(IconData(0xE04A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_java": Icon(IconData(0xE04A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_javascript_light": Icon(
      IconData(0xE04B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_javascript": Icon(IconData(0xE04B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_javascript_1_light": Icon(
      IconData(0xE04B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_javascript_1": Icon(
      IconData(0xE04B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_javascript_2_light": Icon(
      IconData(0xE04B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_javascript_2": Icon(
      IconData(0xE04B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_jenkins_light": Icon(
      IconData(0xE04C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_jenkins": Icon(IconData(0xE04C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_jinja_light": Icon(
      IconData(0xE04D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_jinja": Icon(IconData(0xE04D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_json_light": Icon(IconData(0xE04F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_json": Icon(IconData(0xE04F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_json_1_light": Icon(
      IconData(0xE04F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_json_1": Icon(IconData(0xE04F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_julia_light": Icon(
      IconData(0xE050, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_julia": Icon(IconData(0xE050, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_karma_light": Icon(
      IconData(0xE051, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_karma": Icon(IconData(0xE051, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_kotlin_light": Icon(
      IconData(0xE052, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_kotlin": Icon(IconData(0xE052, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_less_light": Icon(IconData(0xE053, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_less": Icon(IconData(0xE053, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_license_light": Icon(
      IconData(0xE054, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_license": Icon(IconData(0xE054, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_license_1_light": Icon(
      IconData(0xE054, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_license_1": Icon(IconData(0xE054, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_license_2_light": Icon(
      IconData(0xE054, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_license_2": Icon(IconData(0xE054, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_liquid_light": Icon(
      IconData(0xE055, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_liquid": Icon(IconData(0xE055, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_livescript_light": Icon(
      IconData(0xE056, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_livescript": Icon(IconData(0xE056, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_lock_light": Icon(IconData(0xE057, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_lock": Icon(IconData(0xE057, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_lua_light": Icon(IconData(0xE058, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_lua": Icon(IconData(0xE058, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_makefile_light": Icon(
      IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_makefile": Icon(IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_makefile_1_light": Icon(
      IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_makefile_1": Icon(IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_makefile_2_light": Icon(
      IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff627379)),
  "_makefile_2": Icon(IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff6d8086)),
  "_makefile_3_light": Icon(
      IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_makefile_3": Icon(IconData(0xE059, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_markdown_light": Icon(
      IconData(0xE05A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_markdown": Icon(IconData(0xE05A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_maven_light": Icon(
      IconData(0xE05B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_maven": Icon(IconData(0xE05B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_mdo_light": Icon(IconData(0xE05C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_mdo": Icon(IconData(0xE05C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_mustache_light": Icon(
      IconData(0xE05D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_mustache": Icon(IconData(0xE05D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_npm_light": Icon(IconData(0xE05F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff3b4b52)),
  "_npm": Icon(IconData(0xE05F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff41535b)),
  "_npm_1_light": Icon(
      IconData(0xE05F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_npm_1": Icon(IconData(0xE05F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_npm_ignored_light": Icon(
      IconData(0xE060, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff3b4b52)),
  "_npm_ignored": Icon(
      IconData(0xE060, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff41535b)),
  "_nunjucks_light": Icon(
      IconData(0xE061, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_nunjucks": Icon(IconData(0xE061, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_ocaml_light": Icon(
      IconData(0xE062, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_ocaml": Icon(IconData(0xE062, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_odata_light": Icon(
      IconData(0xE063, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_odata": Icon(IconData(0xE063, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_pddl_light": Icon(IconData(0xE064, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_pddl": Icon(IconData(0xE064, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_pdf_light": Icon(IconData(0xE065, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_pdf": Icon(IconData(0xE065, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_perl_light": Icon(IconData(0xE066, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_perl": Icon(IconData(0xE066, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_photoshop_light": Icon(
      IconData(0xE067, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_photoshop": Icon(IconData(0xE067, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_php_light": Icon(IconData(0xE068, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_php": Icon(IconData(0xE068, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_plan_light": Icon(IconData(0xE069, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_plan": Icon(IconData(0xE069, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_platformio_light": Icon(
      IconData(0xE06A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_platformio": Icon(IconData(0xE06A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_powershell_light": Icon(
      IconData(0xE06B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_powershell": Icon(IconData(0xE06B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_pug_light": Icon(IconData(0xE06D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_pug": Icon(IconData(0xE06D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_puppet_light": Icon(
      IconData(0xE06E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_puppet": Icon(IconData(0xE06E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_python_light": Icon(
      IconData(0xE06F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_python": Icon(IconData(0xE06F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_react_light": Icon(
      IconData(0xE071, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_react": Icon(IconData(0xE071, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_react_1_light": Icon(
      IconData(0xE071, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_react_1": Icon(IconData(0xE071, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_react_2_light": Icon(
      IconData(0xE071, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_react_2": Icon(IconData(0xE071, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_reasonml_light": Icon(
      IconData(0xE072, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_reasonml": Icon(IconData(0xE072, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_rollup_light": Icon(
      IconData(0xE073, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_rollup": Icon(IconData(0xE073, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_ruby_light": Icon(IconData(0xE074, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_ruby": Icon(IconData(0xE074, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_rust_light": Icon(IconData(0xE075, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff627379)),
  "_rust": Icon(IconData(0xE075, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff6d8086)),
  "_salesforce_light": Icon(
      IconData(0xE076, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_salesforce": Icon(IconData(0xE076, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_sass_light": Icon(IconData(0xE077, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffdd4b78)),
  "_sass": Icon(IconData(0xE077, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xfff55385)),
  "_sbt_light": Icon(IconData(0xE078, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_sbt": Icon(IconData(0xE078, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_scala_light": Icon(
      IconData(0xE079, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_scala": Icon(IconData(0xE079, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_shell_light": Icon(
      IconData(0xE07C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff455155)),
  "_shell": Icon(IconData(0xE07C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff4d5a5e)),
  "_slim_light": Icon(IconData(0xE07D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_slim": Icon(IconData(0xE07D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_smarty_light": Icon(
      IconData(0xE07E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_smarty": Icon(IconData(0xE07E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_spring_light": Icon(
      IconData(0xE07F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_spring": Icon(IconData(0xE07F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_stylelint_light": Icon(
      IconData(0xE080, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffbfc2c1)),
  "_stylelint": Icon(IconData(0xE080, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffd4d7d6)),
  "_stylelint_1_light": Icon(
      IconData(0xE080, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff455155)),
  "_stylelint_1": Icon(
      IconData(0xE080, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff4d5a5e)),
  "_stylus_light": Icon(
      IconData(0xE081, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_stylus": Icon(IconData(0xE081, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_sublime_light": Icon(
      IconData(0xE082, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_sublime": Icon(IconData(0xE082, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_svg_light": Icon(IconData(0xE083, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_svg": Icon(IconData(0xE083, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_svg_1_light": Icon(
      IconData(0xE083, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_svg_1": Icon(IconData(0xE083, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_swift_light": Icon(
      IconData(0xE084, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_swift": Icon(IconData(0xE084, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_terraform_light": Icon(
      IconData(0xE085, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_terraform": Icon(IconData(0xE085, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_tex_light": Icon(IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_tex": Icon(IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_tex_1_light": Icon(
      IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_tex_1": Icon(IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_tex_2_light": Icon(
      IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_tex_2": Icon(IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_tex_3_light": Icon(
      IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffbfc2c1)),
  "_tex_3": Icon(IconData(0xE086, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffd4d7d6)),
  "_todo": Icon(IconData(0xE088, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff000000)),
  "_tsconfig_light": Icon(
      IconData(0xE089, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_tsconfig": Icon(IconData(0xE089, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_twig_light": Icon(IconData(0xE08A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_twig": Icon(IconData(0xE08A, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_typescript_light": Icon(
      IconData(0xE08B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_typescript": Icon(IconData(0xE08B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_typescript_1_light": Icon(
      IconData(0xE08B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb7b73b)),
  "_typescript_1": Icon(
      IconData(0xE08B, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcbcb41)),
  "_vala_light": Icon(IconData(0xE08C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff627379)),
  "_vala": Icon(IconData(0xE08C, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff6d8086)),
  "_video_light": Icon(
      IconData(0xE08D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffdd4b78)),
  "_video": Icon(IconData(0xE08D, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xfff55385)),
  "_vue_light": Icon(IconData(0xE08E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_vue": Icon(IconData(0xE08E, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_wasm_light": Icon(IconData(0xE08F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_wasm": Icon(IconData(0xE08F, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_wat_light": Icon(IconData(0xE090, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_wat": Icon(IconData(0xE090, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_webpack_light": Icon(
      IconData(0xE091, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_webpack": Icon(IconData(0xE091, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_wgt_light": Icon(IconData(0xE092, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_wgt": Icon(IconData(0xE092, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_windows_light": Icon(
      IconData(0xE093, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_windows": Icon(IconData(0xE093, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_word_light": Icon(IconData(0xE094, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_word": Icon(IconData(0xE094, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_xls_light": Icon(IconData(0xE095, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff7fae42)),
  "_xls": Icon(IconData(0xE095, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff8dc149)),
  "_xml_light": Icon(IconData(0xE096, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc6d2e)),
  "_xml": Icon(IconData(0xE096, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffe37933)),
  "_yarn_light": Icon(IconData(0xE097, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff498ba7)),
  "_yarn": Icon(IconData(0xE097, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff519aba)),
  "_yml_light": Icon(IconData(0xE098, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff9068b0)),
  "_yml": Icon(IconData(0xE098, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffa074c4)),
  "_zip_light": Icon(IconData(0xE099, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffb8383d)),
  "_zip": Icon(IconData(0xE099, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xffcc3e44)),
  "_zip_1_light": Icon(
      IconData(0xE099, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff627379)),
  "_zip_1": Icon(IconData(0xE099, fontFamily: "Seti", fontPackage: "seti"),
      color: Color(0xff6d8086)),
};
const setiMeta = {
  "extensions": {
    "bsl": "_bsl",
    "mdo": "_mdo",
    "asm": "_asm",
    "s": "_asm",
    "h": "_c_1",
    "aspx": "_html",
    "ascx": "_html_1",
    "asax": "_html_2",
    "master": "_html_2",
    "hh": "_cpp_1",
    "hpp": "_cpp_1",
    "hxx": "_cpp_1",
    "edn": "_clojure_1",
    "cfc": "_coldfusion",
    "cfm": "_coldfusion",
    "config": "_config",
    "cfg": "_config",
    "conf": "_config",
    "cr": "_crystal",
    "ecr": "_crystal_embedded",
    "slang": "_crystal_embedded",
    "cson": "_json",
    "css.map": "_css",
    "sss": "_css",
    "csv": "_csv",
    "xls": "_xls",
    "xlsx": "_xls",
    "cake": "_cake",
    "ctp": "_cake_php",
    "d": "_d",
    "doc": "_word",
    "docx": "_word",
    "ejs": "_ejs",
    "ex": "_elixir",
    "exs": "_elixir_script",
    "elm": "_elm",
    "ico": "_favicon",
    "gitignore": "_git",
    "gitconfig": "_git",
    "gitkeep": "_git",
    "gitattributes": "_git",
    "gitmodules": "_git",
    "slide": "_go",
    "article": "_go",
    "gradle": "_gradle",
    "gsp": "_grails",
    "gql": "_graphql",
    "graphql": "_graphql",
    "haml": "_haml",
    "hs": "_haskell",
    "lhs": "_haskell",
    "hx": "_haxe",
    "hxs": "_haxe_1",
    "hxp": "_haxe_2",
    "hxml": "_haxe_3",
    "class": "_java",
    "classpath": "_java",
    "js.map": "_javascript",
    "spec.js": "_javascript_1",
    "test.js": "_javascript_1",
    "es": "_javascript",
    "es5": "_javascript",
    "es7": "_javascript",
    "jinja": "_jinja",
    "jinja2": "_jinja",
    "jl": "_julia",
    "kt": "_kotlin",
    "kts": "_kotlin",
    "dart": "_dart",
    "liquid": "_liquid",
    "ls": "_livescript",
    "argdown": "_argdown",
    "ad": "_argdown",
    "mustache": "_mustache",
    "stache": "_mustache",
    "njk": "_nunjucks",
    "nunjucks": "_nunjucks",
    "nunjs": "_nunjucks",
    "nunj": "_nunjucks",
    "njs": "_nunjucks",
    "nj": "_nunjucks",
    "npm-debug.log": "_npm",
    "npmignore": "_npm_1",
    "npmrc": "_npm_1",
    "ml": "_ocaml",
    "mli": "_ocaml",
    "cmx": "_ocaml",
    "cmxa": "_ocaml",
    "odata": "_odata",
    "php.inc": "_php",
    "pddl": "_pddl",
    "plan": "_plan",
    "happenings": "_happenings",
    "pug": "_pug",
    "pp": "_puppet",
    "epp": "_puppet",
    "spec.jsx": "_react_1",
    "test.jsx": "_react_1",
    "cjsx": "_react",
    "spec.tsx": "_react_2",
    "test.tsx": "_react_2",
    "re": "_reasonml",
    "r": "_R",
    "erb": "_html_erb",
    "erb.html": "_html_erb",
    "html.erb": "_html_erb",
    "sass": "_sass",
    "springbeans": "_spring",
    "slim": "_slim",
    "smarty.tpl": "_smarty",
    "sbt": "_sbt",
    "scala": "_scala",
    "sol": "_ethereum",
    "styl": "_stylus",
    "tf": "_terraform",
    "tf.json": "_terraform",
    "tfvars": "_terraform",
    "tex": "_tex",
    "sty": "_tex_1",
    "dtx": "_tex_2",
    "ins": "_tex_3",
    "toml": "_config",
    "twig": "_twig",
    "spec.ts": "_typescript_1",
    "test.ts": "_typescript_1",
    "vala": "_vala",
    "vapi": "_vala",
    "vue": "_vue",
    "wasm": "_wasm",
    "wat": "_wat",
    "jar": "_zip",
    "zip": "_zip_1",
    "wgt": "_wgt",
    "ai": "_illustrator",
    "psd": "_photoshop",
    "pdf": "_pdf",
    "eot": "_font",
    "ttf": "_font",
    "woff": "_font",
    "woff2": "_font",
    "gif": "_image",
    "jpg": "_image",
    "jpeg": "_image",
    "png": "_image",
    "pxm": "_image",
    "svg": "_svg",
    "svgx": "_image",
    "sublime-project": "_sublime",
    "sublime-workspace": "_sublime",
    "component": "_salesforce",
    "cls": "_salesforce",
    "fish": "_shell",
    "mov": "_video",
    "ogv": "_video",
    "webm": "_video",
    "avi": "_video",
    "mpg": "_video",
    "mp4": "_video",
    "mp3": "_audio",
    "ogg": "_audio",
    "wav": "_audio",
    "flac": "_audio",
    "3ds": "_svg_1",
    "3dm": "_svg_1",
    "stl": "_svg_1",
    "obj": "_svg_1",
    "dae": "_svg_1",
    "babelrc": "_babel",
    "bowerrc": "_bower",
    "dockerignore": "_docker_1",
    "codeclimate.yml": "_code-climate",
    "eslintrc": "_eslint",
    "eslintrc.js": "_eslint",
    "eslintrc.yaml": "_eslint",
    "eslintrc.yml": "_eslint",
    "eslintrc.json": "_eslint",
    "eslintignore": "_eslint_1",
    "firebaserc": "_firebase",
    "jshintrc": "_javascript_2",
    "jscsrc": "_javascript_2",
    "stylelintrc": "_stylelint",
    "stylelintrc.json": "_stylelint",
    "stylelintrc.yaml": "_stylelint",
    "stylelintrc.yml": "_stylelint",
    "stylelintrc.js": "_stylelint",
    "stylelintignore": "_stylelint_1",
    "direnv": "_config",
    "env": "_config",
    "static": "_config",
    "editorconfig": "_config",
    "slugignore": "_config",
    "tmp": "_clock_1",
    "htaccess": "_config",
    "key": "_lock",
    "cert": "_lock",
    "ds_store": "_ignored"
  },
  "names": {
    "mix": "_hex",
    "karma.conf.js": "_karma",
    "karma.conf.coffee": "_karma",
    "readme.md": "_info",
    "changelog.md": "_clock",
    "changelog": "_clock",
    "changes.md": "_clock",
    "version.md": "_clock",
    "version": "_clock",
    "mvnw": "_maven",
    "tsconfig.json": "_tsconfig",
    "swagger.json": "_json_1",
    "swagger.yml": "_json_1",
    "swagger.yaml": "_json_1",
    "mime.types": "_config",
    "jenkinsfile": "_jenkins",
    "bower.json": "_bower",
    "docker-healthcheck": "_docker_2",
    "docker-compose.yml": "_docker_3",
    "docker-compose.yaml": "_docker_3",
    "docker-compose.override.yml": "_docker_3",
    "docker-compose.override.yaml": "_docker_3",
    "firebase.json": "_firebase",
    "geckodriver": "_firefox",
    "gruntfile.js": "_grunt",
    "gruntfile.babel.js": "_grunt",
    "gruntfile.coffee": "_grunt",
    "gulpfile": "_gulp",
    "ionic.config.json": "_ionic",
    "ionic.project": "_ionic",
    "platformio.ini": "_platformio",
    "rollup.config.js": "_rollup",
    "sass-lint.yml": "_sass",
    "stylelint.config.js": "_stylelint",
    "yarn.clean": "_yarn",
    "yarn.lock": "_yarn",
    "webpack.config.js": "_webpack",
    "webpack.config.build.js": "_webpack",
    "webpack.common.js": "_webpack",
    "webpack.dev.js": "_webpack",
    "webpack.prod.js": "_webpack",
    "license": "_license",
    "licence": "_license",
    "copying": "_license",
    "compiling": "_license_1",
    "contributing": "_license_2",
    "qmakefile": "_makefile_1",
    "omakefile": "_makefile_2",
    "cmakelists.txt": "_makefile_3",
    "procfile": "_heroku",
    "todo": "_todo",
    "npm-debug.log": "_npm_ignored"
  }
};
const setiLightMeta = {
  "extensions": {
    "bsl": "_bsl_light",
    "mdo": "_mdo_light",
    "asm": "_asm_light",
    "s": "_asm_light",
    "h": "_c_1_light",
    "aspx": "_html_light",
    "ascx": "_html_1_light",
    "asax": "_html_2_light",
    "master": "_html_2_light",
    "hh": "_cpp_1_light",
    "hpp": "_cpp_1_light",
    "hxx": "_cpp_1_light",
    "edn": "_clojure_1_light",
    "cfc": "_coldfusion_light",
    "cfm": "_coldfusion_light",
    "config": "_config_light",
    "cfg": "_config_light",
    "conf": "_config_light",
    "cr": "_crystal_light",
    "ecr": "_crystal_embedded_light",
    "slang": "_crystal_embedded_light",
    "cson": "_json_light",
    "css.map": "_css_light",
    "sss": "_css_light",
    "csv": "_csv_light",
    "xls": "_xls_light",
    "xlsx": "_xls_light",
    "cake": "_cake_light",
    "ctp": "_cake_php_light",
    "d": "_d_light",
    "doc": "_word_light",
    "docx": "_word_light",
    "ejs": "_ejs_light",
    "ex": "_elixir_light",
    "exs": "_elixir_script_light",
    "elm": "_elm_light",
    "ico": "_favicon_light",
    "gitignore": "_git_light",
    "gitconfig": "_git_light",
    "gitkeep": "_git_light",
    "gitattributes": "_git_light",
    "gitmodules": "_git_light",
    "slide": "_go_light",
    "article": "_go_light",
    "gradle": "_gradle_light",
    "gsp": "_grails_light",
    "gql": "_graphql_light",
    "graphql": "_graphql_light",
    "haml": "_haml_light",
    "hs": "_haskell_light",
    "lhs": "_haskell_light",
    "hx": "_haxe_light",
    "hxs": "_haxe_1_light",
    "hxp": "_haxe_2_light",
    "hxml": "_haxe_3_light",
    "class": "_java_light",
    "classpath": "_java_light",
    "js.map": "_javascript_light",
    "spec.js": "_javascript_1_light",
    "test.js": "_javascript_1_light",
    "es": "_javascript_light",
    "es5": "_javascript_light",
    "es7": "_javascript_light",
    "jinja": "_jinja_light",
    "jinja2": "_jinja_light",
    "jl": "_julia_light",
    "kt": "_kotlin_light",
    "kts": "_kotlin_light",
    "dart": "_dart_light",
    "liquid": "_liquid_light",
    "ls": "_livescript_light",
    "argdown": "_argdown_light",
    "ad": "_argdown_light",
    "mustache": "_mustache_light",
    "stache": "_mustache_light",
    "njk": "_nunjucks_light",
    "nunjucks": "_nunjucks_light",
    "nunjs": "_nunjucks_light",
    "nunj": "_nunjucks_light",
    "njs": "_nunjucks_light",
    "nj": "_nunjucks_light",
    "npm-debug.log": "_npm_light",
    "npmignore": "_npm_1_light",
    "npmrc": "_npm_1_light",
    "ml": "_ocaml_light",
    "mli": "_ocaml_light",
    "cmx": "_ocaml_light",
    "cmxa": "_ocaml_light",
    "odata": "_odata_light",
    "php.inc": "_php_light",
    "pddl": "_pddl_light",
    "plan": "_plan_light",
    "happenings": "_happenings_light",
    "pug": "_pug_light",
    "pp": "_puppet_light",
    "epp": "_puppet_light",
    "spec.jsx": "_react_1_light",
    "test.jsx": "_react_1_light",
    "cjsx": "_react_light",
    "spec.tsx": "_react_2_light",
    "test.tsx": "_react_2_light",
    "re": "_reasonml_light",
    "r": "_R_light",
    "erb": "_html_erb_light",
    "erb.html": "_html_erb_light",
    "html.erb": "_html_erb_light",
    "sass": "_sass_light",
    "springbeans": "_spring_light",
    "slim": "_slim_light",
    "smarty.tpl": "_smarty_light",
    "sbt": "_sbt_light",
    "scala": "_scala_light",
    "sol": "_ethereum_light",
    "styl": "_stylus_light",
    "tf": "_terraform_light",
    "tf.json": "_terraform_light",
    "tfvars": "_terraform_light",
    "tex": "_tex_light",
    "sty": "_tex_1_light",
    "dtx": "_tex_2_light",
    "ins": "_tex_3_light",
    "toml": "_config_light",
    "twig": "_twig_light",
    "spec.ts": "_typescript_1_light",
    "test.ts": "_typescript_1_light",
    "vala": "_vala_light",
    "vapi": "_vala_light",
    "vue": "_vue_light",
    "wasm": "_wasm_light",
    "wat": "_wat_light",
    "jar": "_zip_light",
    "zip": "_zip_1_light",
    "wgt": "_wgt_light",
    "ai": "_illustrator_light",
    "psd": "_photoshop_light",
    "pdf": "_pdf_light",
    "eot": "_font_light",
    "ttf": "_font_light",
    "woff": "_font_light",
    "woff2": "_font_light",
    "gif": "_image_light",
    "jpg": "_image_light",
    "jpeg": "_image_light",
    "png": "_image_light",
    "pxm": "_image_light",
    "svg": "_svg_light",
    "svgx": "_image_light",
    "sublime-project": "_sublime_light",
    "sublime-workspace": "_sublime_light",
    "component": "_salesforce_light",
    "cls": "_salesforce_light",
    "fish": "_shell_light",
    "mov": "_video_light",
    "ogv": "_video_light",
    "webm": "_video_light",
    "avi": "_video_light",
    "mpg": "_video_light",
    "mp4": "_video_light",
    "mp3": "_audio_light",
    "ogg": "_audio_light",
    "wav": "_audio_light",
    "flac": "_audio_light",
    "3ds": "_svg_1_light",
    "3dm": "_svg_1_light",
    "stl": "_svg_1_light",
    "obj": "_svg_1_light",
    "dae": "_svg_1_light",
    "babelrc": "_babel_light",
    "bowerrc": "_bower_light",
    "dockerignore": "_docker_1_light",
    "codeclimate.yml": "_code-climate_light",
    "eslintrc": "_eslint_light",
    "eslintrc.js": "_eslint_light",
    "eslintrc.yaml": "_eslint_light",
    "eslintrc.yml": "_eslint_light",
    "eslintrc.json": "_eslint_light",
    "eslintignore": "_eslint_1_light",
    "firebaserc": "_firebase_light",
    "jshintrc": "_javascript_2_light",
    "jscsrc": "_javascript_2_light",
    "stylelintrc": "_stylelint_light",
    "stylelintrc.json": "_stylelint_light",
    "stylelintrc.yaml": "_stylelint_light",
    "stylelintrc.yml": "_stylelint_light",
    "stylelintrc.js": "_stylelint_light",
    "stylelintignore": "_stylelint_1_light",
    "direnv": "_config_light",
    "env": "_config_light",
    "static": "_config_light",
    "editorconfig": "_config_light",
    "slugignore": "_config_light",
    "tmp": "_clock_1_light",
    "htaccess": "_config_light",
    "key": "_lock_light",
    "cert": "_lock_light",
    "ds_store": "_ignored_light"
  },
  "names": {
    "mix": "_hex_light",
    "karma.conf.js": "_karma_light",
    "karma.conf.coffee": "_karma_light",
    "readme.md": "_info_light",
    "changelog.md": "_clock_light",
    "changelog": "_clock_light",
    "changes.md": "_clock_light",
    "version.md": "_clock_light",
    "version": "_clock_light",
    "mvnw": "_maven_light",
    "tsconfig.json": "_tsconfig_light",
    "swagger.json": "_json_1_light",
    "swagger.yml": "_json_1_light",
    "swagger.yaml": "_json_1_light",
    "mime.types": "_config_light",
    "jenkinsfile": "_jenkins_light",
    "bower.json": "_bower_light",
    "docker-healthcheck": "_docker_2_light",
    "docker-compose.yml": "_docker_3_light",
    "docker-compose.yaml": "_docker_3_light",
    "docker-compose.override.yml": "_docker_3_light",
    "docker-compose.override.yaml": "_docker_3_light",
    "firebase.json": "_firebase_light",
    "geckodriver": "_firefox_light",
    "gruntfile.js": "_grunt_light",
    "gruntfile.babel.js": "_grunt_light",
    "gruntfile.coffee": "_grunt_light",
    "gulpfile": "_gulp_light",
    "ionic.config.json": "_ionic_light",
    "ionic.project": "_ionic_light",
    "platformio.ini": "_platformio_light",
    "rollup.config.js": "_rollup_light",
    "sass-lint.yml": "_sass_light",
    "stylelint.config.js": "_stylelint_light",
    "yarn.clean": "_yarn_light",
    "yarn.lock": "_yarn_light",
    "webpack.config.js": "_webpack_light",
    "webpack.config.build.js": "_webpack_light",
    "webpack.common.js": "_webpack_light",
    "webpack.dev.js": "_webpack_light",
    "webpack.prod.js": "_webpack_light",
    "license": "_license_light",
    "licence": "_license_light",
    "copying": "_license_light",
    "compiling": "_license_1_light",
    "contributing": "_license_2_light",
    "qmakefile": "_makefile_1_light",
    "omakefile": "_makefile_2_light",
    "cmakelists.txt": "_makefile_3_light",
    "procfile": "_heroku_light",
    "npm-debug.log": "_npm_ignored_light"
  }
};
